import unittest

from project_toki.grammar_parser import GrammarParser
from project_toki.phrase import Phrase
from project_toki.phrase_comparer import PhraseComparer


class TestGrammarPuPreface(unittest.TestCase):
    COMPARER: PhraseComparer = PhraseComparer()

    def test_preface(self):
        self.COMPARER.compare_phrases(
            GrammarParser.parse_text("mi open lon nimi sewi."),
            Phrase.from_lines(
                [
                    "TEXT",
                    "└── SENTENCE",
                    "    ├── NOUN_PHRASE",
                    '    │   └── NOUN: "mi"',
                    "    ├── VERB_PHRASE",
                    '    │   ├── VERB: "open"',
                    "    │   └── PREPOSITION_PHRASE",
                    '    │       ├── PREPOSITION: "lon"',
                    "    │       └── NOUN_PHRASE",
                    '    │           ├── NOUN: "nimi"',
                    "    │           └── ADJECTIVE_PHRASE",
                    '    │               └── ADJECTIVE: "sewi"',
                    "    └── .",
                ],
            ),
        )
        self.COMPARER.compare_phrases(
            GrammarParser.parse_text("sina pu a!"),
            Phrase.from_lines(
                [
                    "TEXT",
                    "└── SENTENCE",
                    "    ├── NOUN_PHRASE",
                    '    │   └── NOUN: "sina"',
                    "    ├── VERB_PHRASE",
                    "    │   └── ADJECTIVE_PHRASE",
                    '    │       └── ADJECTIVE: "pu"',
                    '    ├── PARTICLE: "a"',
                    "    └── !",
                ],
            ),
        )
        self.COMPARER.compare_phrases(
            GrammarParser.parse_text(
                "toki pona li tan seme? tenpo pini la mi wile sona e kon ale kepeken nimi lili.",
            ),
            Phrase.from_lines(
                [
                    "TEXT",
                    "├── SENTENCE",
                    "│   ├── NOUN_PHRASE",
                    '│   │   ├── NOUN: "toki"',
                    "│   │   └── ADJECTIVE_PHRASE",
                    '│   │       └── ADJECTIVE: "pona"',
                    '│   ├── PARTICLE: "li"',
                    "│   ├── VERB_PHRASE",
                    "│   │   └── PREPOSITION_PHRASE",
                    '│   │       ├── PREPOSITION: "tan"',
                    "│   │       └── NOUN_PHRASE",
                    '│   │           └── NOUN: "seme"',
                    "│   └── ?",
                    "└── SENTENCE",
                    "    ├── NOUN_PHRASE",
                    '    │   ├── NOUN: "tenpo"',
                    "    │   └── ADJECTIVE_PHRASE",
                    '    │       └── ADJECTIVE: "pini"',
                    '    ├── PARTICLE: "la"',
                    "    ├── NOUN_PHRASE",
                    '    │   └── NOUN: "mi"',
                    "    ├── VERB_PHRASE",
                    '    │   ├── PREVERB: "wile"',
                    '    │   ├── VERB: "sona"',
                    '    │   ├── PARTICLE: "e"',
                    "    │   ├── NOUN_PHRASE",
                    '    │   │   ├── NOUN: "kon"',
                    "    │   │   └── ADJECTIVE_PHRASE",
                    '    │   │       └── ADJECTIVE: "ale"',
                    "    │   └── PREPOSITION_PHRASE",
                    '    │       ├── PREPOSITION: "kepeken"',
                    "    │       └── NOUN_PHRASE",
                    '    │           ├── NOUN: "nimi"',
                    "    │           └── ADJECTIVE_PHRASE",
                    '    │               └── ADJECTIVE: "lili"',
                    "    └── .",
                ],
            ),
        )
        self.COMPARER.compare_phrases(
            GrammarParser.parse_text(
                "mi lukin e kon mi. mi kama sona e toki mute. mi musi. mi pali e nasin toki lili. ona li pona e toki insa mi.",
            ),
            Phrase.from_lines(
                [
                    "TEXT",
                    "├── SENTENCE",
                    "│   ├── NOUN_PHRASE",
                    '│   │   └── NOUN: "mi"',
                    "│   ├── VERB_PHRASE",
                    '│   │   ├── VERB: "lukin"',
                    '│   │   ├── PARTICLE: "e"',
                    "│   │   └── NOUN_PHRASE",
                    '│   │       ├── NOUN: "kon"',
                    "│   │       └── ADJECTIVE_PHRASE",
                    '│   │           └── ADJECTIVE: "mi"',
                    "│   └── .",
                    "├── SENTENCE",
                    "│   ├── NOUN_PHRASE",
                    '│   │   └── NOUN: "mi"',
                    "│   ├── VERB_PHRASE",
                    '│   │   ├── PREVERB: "kama"',
                    '│   │   ├── VERB: "sona"',
                    '│   │   ├── PARTICLE: "e"',
                    "│   │   └── NOUN_PHRASE",
                    '│   │       ├── NOUN: "toki"',
                    "│   │       └── ADJECTIVE_PHRASE",
                    '│   │           └── ADJECTIVE: "mute"',
                    "│   └── .",
                    "├── SENTENCE",
                    "│   ├── NOUN_PHRASE",
                    '│   │   └── NOUN: "mi"',
                    "│   ├── VERB_PHRASE",
                    "│   │   └── ADJECTIVE_PHRASE",
                    '│   │       └── ADJECTIVE: "musi"',
                    "│   └── .",
                    "├── SENTENCE",
                    "│   ├── NOUN_PHRASE",
                    '│   │   └── NOUN: "mi"',
                    "│   ├── VERB_PHRASE",
                    '│   │   ├── VERB: "pali"',
                    '│   │   ├── PARTICLE: "e"',
                    "│   │   └── NOUN_PHRASE",
                    '│   │       ├── NOUN: "nasin"',
                    "│   │       └── ADJECTIVE_PHRASE",
                    '│   │           ├── ADJECTIVE: "toki"',
                    '│   │           └── ADJECTIVE: "lili"',
                    "│   └── .",
                    "└── SENTENCE",
                    "    ├── NOUN_PHRASE",
                    '    │   └── NOUN: "ona"',
                    '    ├── PARTICLE: "li"',
                    "    ├── VERB_PHRASE",
                    '    │   ├── VERB: "pona"',
                    '    │   ├── PARTICLE: "e"',
                    "    │   └── NOUN_PHRASE",
                    '    │       ├── NOUN: "toki"',
                    "    │       └── ADJECTIVE_PHRASE",
                    '    │           ├── ADJECTIVE: "insa"',
                    '    │           └── ADJECTIVE: "mi"',
                    "    └── .",
                ],
            ),
        )
        self.COMPARER.compare_phrases(
            GrammarParser.parse_text(
                "mi pana e toki lili mi tawa jan ale lon ilo lipu lon tenpo pini. kulupu lili li kama. ona li olin e toki pona.",
            ),
            Phrase.from_lines(
                [
                    "TEXT",
                    "├── SENTENCE",
                    "│   ├── NOUN_PHRASE",
                    '│   │   └── NOUN: "mi"',
                    "│   ├── VERB_PHRASE",
                    '│   │   ├── VERB: "pana"',
                    '│   │   ├── PARTICLE: "e"',
                    "│   │   ├── NOUN_PHRASE",
                    '│   │   │   ├── NOUN: "toki"',
                    "│   │   │   └── ADJECTIVE_PHRASE",
                    '│   │   │       ├── ADJECTIVE: "lili"',
                    '│   │   │       └── ADJECTIVE: "mi"',
                    "│   │   ├── PREPOSITION_PHRASE",
                    '│   │   │   ├── PREPOSITION: "tawa"',
                    "│   │   │   └── NOUN_PHRASE",
                    '│   │   │       ├── NOUN: "jan"',
                    "│   │   │       └── ADJECTIVE_PHRASE",
                    '│   │   │           └── ADJECTIVE: "ale"',
                    "│   │   ├── PREPOSITION_PHRASE",
                    '│   │   │   ├── PREPOSITION: "lon"',
                    "│   │   │   └── NOUN_PHRASE",
                    '│   │   │       ├── NOUN: "ilo"',
                    "│   │   │       └── ADJECTIVE_PHRASE",
                    '│   │   │           └── ADJECTIVE: "lipu"',
                    "│   │   └── PREPOSITION_PHRASE",
                    '│   │       ├── PREPOSITION: "lon"',
                    "│   │       └── NOUN_PHRASE",
                    '│   │           ├── NOUN: "tenpo"',
                    "│   │           └── ADJECTIVE_PHRASE",
                    '│   │               └── ADJECTIVE: "pini"',
                    "│   └── .",
                    "├── SENTENCE",
                    "│   ├── NOUN_PHRASE",
                    '│   │   ├── NOUN: "kulupu"',
                    "│   │   └── ADJECTIVE_PHRASE",
                    '│   │       └── ADJECTIVE: "lili"',
                    '│   ├── PARTICLE: "li"',
                    "│   ├── VERB_PHRASE",
                    "│   │   └── ADJECTIVE_PHRASE",
                    '│   │       └── ADJECTIVE: "kama"',
                    "│   └── .",
                    "└── SENTENCE",
                    "    ├── NOUN_PHRASE",
                    '    │   └── NOUN: "ona"',
                    '    ├── PARTICLE: "li"',
                    "    ├── VERB_PHRASE",
                    '    │   ├── VERB: "olin"',
                    '    │   ├── PARTICLE: "e"',
                    "    │   └── NOUN_PHRASE",
                    '    │       ├── NOUN: "toki"',
                    "    │       └── ADJECTIVE_PHRASE",
                    '    │           └── ADJECTIVE: "pona"',
                    "    └── .",
                ],
            ),
        )
        self.COMPARER.compare_phrases(
            GrammarParser.parse_text(
                "pu la mi wile pana e selo pini pi toki pona. nasin ni la mi kepeken toki pona.",
            ),
            Phrase.from_lines(
                [
                    "TEXT",
                    "├── SENTENCE",
                    "│   ├── ADJECTIVE_PHRASE",
                    '│   │   └── ADJECTIVE: "pu"',
                    '│   ├── PARTICLE: "la"',
                    "│   ├── NOUN_PHRASE",
                    '│   │   └── NOUN: "mi"',
                    "│   ├── VERB_PHRASE",
                    '│   │   ├── PREVERB: "wile"',
                    '│   │   ├── VERB: "pana"',
                    '│   │   ├── PARTICLE: "e"',
                    "│   │   └── NOUN_PHRASE",
                    '│   │       ├── NOUN: "selo"',
                    "│   │       ├── ADJECTIVE_PHRASE",
                    '│   │       │   └── ADJECTIVE: "pini"',
                    '│   │       ├── PARTICLE: "pi"',
                    '│   │       ├── NOUN: "toki"',
                    "│   │       └── ADJECTIVE_PHRASE",
                    '│   │           └── ADJECTIVE: "pona"',
                    "│   └── .",
                    "└── SENTENCE",
                    "    ├── NOUN_PHRASE",
                    '    │   ├── NOUN: "nasin"',
                    "    │   └── ADJECTIVE_PHRASE",
                    '    │       └── ADJECTIVE: "ni"',
                    '    ├── PARTICLE: "la"',
                    "    ├── NOUN_PHRASE",
                    '    │   └── NOUN: "mi"',
                    "    ├── VERB_PHRASE",
                    "    │   └── PREPOSITION_PHRASE",
                    '    │       ├── PREPOSITION: "kepeken"',
                    "    │       └── NOUN_PHRASE",
                    '    │           ├── NOUN: "toki"',
                    "    │           └── ADJECTIVE_PHRASE",
                    '    │               └── ADJECTIVE: "pona"',
                    "    └── .",
                ],
            ),
        )
        self.COMPARER.compare_phrases(
            GrammarParser.parse_text("jan Sonja"),
            Phrase.from_lines(
                [
                    "TEXT",
                    "└── SENTENCE",
                    "    └── NOUN_PHRASE",
                    '        ├── NOUN: "jan"',
                    "        └── ADJECTIVE_PHRASE",
                    '            └── ADJECTIVE: "Sonja"',
                ],
            ),
        )
